site_name: Advanced Higher Computer Science

nav:
    - Home: 'index.md'
    - Software Design and Development:
      - Analysis:
        - Feasability Studies: '1.1-feasability-studies.md'
        - Project Planning: '1.2-project-planning.md'
        - Requirement Specifications: '1.3-requirement-specifications.md'
        - UML: '1.4-uml.md'
        - Analysis Tasks: 
          - Task One: '1.5.1-task-one.md'
          - Task Two: '1.5.2-task-two.md'
          - Task Three: '1.5.3-task-three.md'
          - Task Four: '1.5.4-task-four.md'
      - Implementation:
        - Arrays and Records:
          - Parrallel Arrays: '3.1-parallel-1d-arrays.md'
          - Records: '3.2-records.md'
          - Arrays of Records: '3.3-arrays-of-records.md'
          - 2d Arrays: '3.4-2d-arrays.md'
        - Object Orientated Programming:
          - Object: '4.1-objects.md'
          - Arrays of Objects: '3.5-arrays-of-objects.md'
          - Sub-classes: '4.3-sub-class.md'
          - Encapsulation: '4.4-encapsulation.md'
          - Polymorphism: '4.5-polymorphism.md'
          - Example: '4.6-complete-working-example.md'
        - SQL and Python: '5.1-sqlite-with-python.md'
        - Searches and Sorts:
          - Binary Search: '6.1-binary-search.md'
          - Insertation Sort: '6.2-insertation-sort.md'
          - Bubble Sort: '6.3-bubble-sort.md'
    - Program Challenges:
      - Overview: 'program-challenges/index.md'
      - 🔥:
        - Name Change: 'program-challenges/level-1/Name Change.md'
        - Area Calc: 'program-challenges/level-1/Area Calc.md'
        - Largest Number: 'program-challenges/level-1/Largest Number.md'
        - Number Changer: 'program-challenges/level-1/Number Changer.md'
        - Jim's Bonus Scheme: "program-challenges/level-1/Jim's Bonus Scheme.md"
      - 🔥🔥:
        - Bigger and Bigger: 'program-challenges/level-2/Bigger and Bigger.md'
        - Form Chooser: 'program-challenges/level-2/Form Chooser.md'
        - Taxi Fare: 'program-challenges/level-2/Taxi Fare.md'
        - Password Check: 'program-challenges/level-2/Password Check.md'
        - Secret Agent: 'program-challenges/level-2/Secret Agent.md'
        - New Email: 'program-challenges/level-2/New Email.md'
        - Bonus Payment: 'program-challenges/level-2/Bonus Payment.md'
        - BMI Checker: 'program-challenges/level-2/BMI Checker.md'
        - Magic 8 Ball: 'program-challenges/level-2/Magic 8 Ball.md'
        - km to Miles: 'program-challenges/level-2/km to Miles.md'
        - Random Number Generator: 'program-challenges/level-2/Random Number Generator.md'
      - 🔥🔥🔥:
        - Ice Cream!: 'program-challenges/level-3/Ice Cream!.md'
        - Cake Maker: 'program-challenges/level-3/Cake Maker.md'
        - Five A Day: 'program-challenges/level-3/Five A Day.md'
        - Squares and Cubes: 'program-challenges/level-3/Squares and Cubes.md'
        - Lower Case: 'program-challenges/level-3/Lower Case.md'
        - Go Kart: 'program-challenges/level-3/Go Kart.md'
        - Pick A Card: 'program-challenges/level-3/Pick A Card.md'
        - Darts: 'program-challenges/level-3/Darts.md'
        - Averages: 'program-challenges/level-3/Averages.md'
        - Times Tables: 'program-challenges/level-3/Times Tables.md'
      - 🔥🔥🔥🔥:
        - Bingo!: 'program-challenges/level-4/Bingo!.md'
        - OCR Tech: 'program-challenges/level-4/OCR Tech.md'
        - OCR FC - Goals Array: 'program-challenges/level-4/OCR FC - Goals Array.md'
        - Game Time - Day Of The Week: 'program-challenges/level-4/Game Time - Day Of The Week.md'
        - Logging In: 'program-challenges/level-4/Logging In.md'
        - Email Validator: 'program-challenges/level-4/Email Validator.md'
        - Pin Checker: 'program-challenges/level-4/Pin Checker.md'
        - 6th Form Admissions: 'program-challenges/level-4/6th Form Admissions.md'
        - Free Electricity!: 'program-challenges/level-4/Free Electricity!.md'
        - How Many Cars?: 'program-challenges/level-4/How Many Cars?.md'
      - 🔥🔥🔥🔥🔥:
        - Game Time - Total Time: 'program-challenges/level-5/Game Time - Total Time.md'
        - Inverse Image: 'program-challenges/level-5/Inverse Image.md'
        - Battleships: 'program-challenges/level-5/Battleships.md'
    - Project:
      - Description of the Problem: '7.1-description-of-the-problem.md'
        
      
markdown_extensions:
      - admonition
      - pymdownx.details
      - def_list
      - pymdownx.critic
      - pymdownx.caret
      - pymdownx.keys
      - pymdownx.mark
      - pymdownx.tilde
      - attr_list
      - md_in_html    
      - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
      - pymdownx.superfences
      - pymdownx.tabbed:
          alternate_style: true
      - pymdownx.highlight:
          use_pygments: true
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
      - pymdownx.inlinehilite
      - pymdownx.snippets
      
theme:
  name: material
  font:
    text: Quicksand
  palette:
    scheme: default
    primary: blue
    accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.path
    #- navigation.footer
    - navigation.tabs
plugins:
  - search
  - glightbox

copyright: Copyright &copy; 2025 Pixel&Wood Computer Science Tuition

extra_css:
  - Styles/extra.css

extra_javascript:
  - scripts/extra.js
    
